export const formulaCategories = [
  "Physics",
  "Chemistry",
  "Laboratory",
] as const;

export type FormulaCategory =
  (typeof formulaCategories)[number];

export type ScienceFormula = {
  slug: string;
  name: string;
  equation: string;
  description: string;
  category: FormulaCategory;
  variables: readonly string[];
  calculatorHref: `/calculators/${string}`;
};

export const scienceFormulas = [
  {
    slug: "newtons-second-law",
    name: "Newton's Second Law",
    equation: "F = m × a",
    description: "Relates net force to mass and acceleration.",
    category: "Physics",
    variables: ["F = force", "m = mass", "a = acceleration"],
    calculatorHref: "/calculators/force-calculator",
  },
  {
    slug: "weight",
    name: "Weight",
    equation: "W = m × g",
    description: "Calculates the gravitational force acting on a mass.",
    category: "Physics",
    variables: ["W = weight", "m = mass", "g = gravitational acceleration"],
    calculatorHref: "/calculators/weight-calculator",
  },
  {
    slug: "momentum",
    name: "Linear Momentum",
    equation: "p = m × v",
    description: "Finds the momentum of an object in linear motion.",
    category: "Physics",
    variables: ["p = momentum", "m = mass", "v = velocity"],
    calculatorHref: "/calculators/momentum-calculator",
  },
  {
    slug: "kinetic-energy",
    name: "Kinetic Energy",
    equation: "Eₖ = ½mv²",
    description: "Calculates energy due to an object's motion.",
    category: "Physics",
    variables: ["Eₖ = kinetic energy", "m = mass", "v = velocity"],
    calculatorHref: "/calculators/kinetic-energy-calculator",
  },
  {
    slug: "work",
    name: "Mechanical Work",
    equation: "W = Fd cos θ",
    description: "Calculates work when force acts through a displacement.",
    category: "Physics",
    variables: ["W = work", "F = force", "d = displacement", "θ = angle"],
    calculatorHref: "/calculators/work-calculator",
  },
  {
    slug: "power",
    name: "Power",
    equation: "P = W ÷ t",
    description: "Measures how quickly work is done or energy is transferred.",
    category: "Physics",
    variables: ["P = power", "W = work", "t = time"],
    calculatorHref: "/calculators/power-calculator",
  },
  {
    slug: "density",
    name: "Density",
    equation: "ρ = m ÷ V",
    description: "Relates the mass of a substance to its volume.",
    category: "Physics",
    variables: ["ρ = density", "m = mass", "V = volume"],
    calculatorHref: "/calculators/density-calculator",
  },
  {
    slug: "pressure",
    name: "Pressure",
    equation: "P = F ÷ A",
    description: "Calculates force distributed over a surface area.",
    category: "Physics",
    variables: ["P = pressure", "F = normal force", "A = area"],
    calculatorHref: "/calculators/pressure-calculator",
  },
  {
    slug: "ohms-law",
    name: "Ohm's Law",
    equation: "V = I × R",
    description: "Connects voltage, current, and electrical resistance.",
    category: "Physics",
    variables: ["V = voltage", "I = current", "R = resistance"],
    calculatorHref: "/calculators/ohms-law-calculator",
  },
  {
    slug: "wave-speed",
    name: "Wave Speed",
    equation: "v = f × λ",
    description: "Relates a wave's speed, frequency, and wavelength.",
    category: "Physics",
    variables: ["v = wave speed", "f = frequency", "λ = wavelength"],
    calculatorHref: "/calculators/wave-speed-calculator",
  },
  {
    slug: "specific-heat",
    name: "Specific Heat",
    equation: "Q = m × c × ΔT",
    description: "Calculates heat transferred during a temperature change.",
    category: "Physics",
    variables: ["Q = heat", "m = mass", "c = specific heat capacity", "ΔT = temperature change"],
    calculatorHref: "/calculators/specific-heat-calculator",
  },
  {
    slug: "molarity",
    name: "Molarity",
    equation: "M = n ÷ V",
    description: "Expresses solution concentration as moles per liter.",
    category: "Chemistry",
    variables: ["M = molarity", "n = moles of solute", "V = solution volume in liters"],
    calculatorHref: "/calculators/molarity-calculator",
  },
  {
    slug: "molality",
    name: "Molality",
    equation: "m = n ÷ kg solvent",
    description: "Expresses concentration as moles per kilogram of solvent.",
    category: "Chemistry",
    variables: ["m = molality", "n = moles of solute", "kg solvent = solvent mass"],
    calculatorHref: "/calculators/molality-calculator",
  },
  {
    slug: "dilution",
    name: "Solution Dilution",
    equation: "C₁V₁ = C₂V₂",
    description: "Relates concentration and volume before and after dilution.",
    category: "Chemistry",
    variables: ["C = concentration", "V = volume", "1 = initial", "2 = final"],
    calculatorHref: "/calculators/dilution-calculator",
  },
  {
    slug: "ideal-gas-law",
    name: "Ideal Gas Law",
    equation: "PV = nRT",
    description: "Relates pressure, volume, amount, and temperature of an ideal gas.",
    category: "Chemistry",
    variables: ["P = pressure", "V = volume", "n = moles", "R = gas constant", "T = temperature"],
    calculatorHref: "/calculators/ideal-gas-law-calculator",
  },
  {
    slug: "ph",
    name: "pH",
    equation: "pH = −log₁₀[H⁺]",
    description: "Calculates acidity from the hydrogen ion concentration.",
    category: "Chemistry",
    variables: ["pH = acidity scale value", "[H⁺] = hydrogen ion concentration"],
    calculatorHref: "/calculators/ph-calculator",
  },
  {
    slug: "percent-yield",
    name: "Percent Yield",
    equation: "% yield = actual ÷ theoretical × 100",
    description: "Compares the measured product yield with the theoretical yield.",
    category: "Chemistry",
    variables: ["actual = measured yield", "theoretical = predicted maximum yield"],
    calculatorHref: "/calculators/percent-yield-calculator",
  },
  {
    slug: "mass-to-moles",
    name: "Mass to Moles",
    equation: "n = m ÷ M",
    description: "Converts sample mass to amount of substance in moles.",
    category: "Chemistry",
    variables: ["n = moles", "m = sample mass", "M = molar mass"],
    calculatorHref: "/calculators/mass-moles-calculator",
  },
  {
    slug: "mole-fraction",
    name: "Mole Fraction",
    equation: "Xᵢ = nᵢ ÷ nₜₒₜₐₗ",
    description: "Finds a component's fraction of the total amount in a mixture.",
    category: "Chemistry",
    variables: ["Xᵢ = mole fraction", "nᵢ = component moles", "nₜₒₜₐₗ = total moles"],
    calculatorHref: "/calculators/mole-fraction-calculator",
  },
  {
    slug: "percent-error",
    name: "Percent Error",
    equation: "% error = |experimental − accepted| ÷ |accepted| × 100",
    description: "Compares an experimental result with an accepted reference value.",
    category: "Laboratory",
    variables: ["experimental = measured value", "accepted = reference value"],
    calculatorHref: "/calculators/percent-error-calculator",
  },
  {
    slug: "percent-difference",
    name: "Percent Difference",
    equation: "% difference = |A − B| ÷ ((|A| + |B|) ÷ 2) × 100",
    description: "Compares two experimental values when neither is an accepted value.",
    category: "Laboratory",
    variables: ["A = first value", "B = second value"],
    calculatorHref: "/calculators/percent-difference-calculator",
  },
  {
    slug: "arithmetic-mean",
    name: "Arithmetic Mean",
    equation: "x̄ = Σx ÷ n",
    description: "Calculates the average of a set of observations.",
    category: "Laboratory",
    variables: ["x̄ = mean", "Σx = sum of values", "n = number of values"],
    calculatorHref: "/calculators/mean-median-mode-calculator",
  },
  {
    slug: "sample-standard-deviation",
    name: "Sample Standard Deviation",
    equation: "s = √(Σ(xᵢ − x̄)² ÷ (n − 1))",
    description: "Measures the spread of sample observations around their mean.",
    category: "Laboratory",
    variables: ["s = sample standard deviation", "xᵢ = each value", "x̄ = sample mean", "n = sample size"],
    calculatorHref: "/calculators/standard-deviation-calculator",
  },
  {
    slug: "coefficient-of-variation",
    name: "Coefficient of Variation",
    equation: "CV = s ÷ x̄ × 100",
    description: "Expresses variability relative to the mean as a percentage.",
    category: "Laboratory",
    variables: ["CV = coefficient of variation", "s = standard deviation", "x̄ = mean"],
    calculatorHref: "/calculators/coefficient-variation-calculator",
  },
  {
    slug: "relative-uncertainty",
    name: "Relative Uncertainty",
    equation: "relative uncertainty = absolute uncertainty ÷ |measured value|",
    description: "Shows measurement uncertainty relative to the measured magnitude.",
    category: "Laboratory",
    variables: ["absolute uncertainty = uncertainty in original units", "measured value = reported result"],
    calculatorHref: "/calculators/measurement-uncertainty-calculator",
  },
  {
    slug: "rate-of-change",
    name: "Average Rate of Change",
    equation: "rate = (y₂ − y₁) ÷ (x₂ − x₁)",
    description: "Calculates the average change in one variable per unit change in another.",
    category: "Laboratory",
    variables: ["y = dependent variable", "x = independent variable"],
    calculatorHref: "/calculators/rate-of-change-calculator",
  },
  {
    slug: "linear-regression",
    name: "Linear Regression",
    equation: "y = mx + b",
    description: "Models a straight-line relationship between two variables.",
    category: "Laboratory",
    variables: ["m = slope", "b = y-intercept", "x = input", "y = predicted output"],
    calculatorHref: "/calculators/linear-regression-calculator",
  },
] as const satisfies readonly ScienceFormula[];
